version: "3"

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    ports:
      - 9090:9090
    environment:
      NIFI_WEB_HTTP_PORT: 9090
    networks:
      - spark-net

networks:
  spark-net:
    external:
      name: spark-net
